// frontend/src/App.vue
<template>
  <div>
    <header class="bg-blue-500 flex justify-center items-center py-4 select-none">
      <img src="./assets/images/logo.png" alt="logo" class="w-40" />
    </header>
    <form class="flex justify-between items-center px-4 py-2">
      <input type="text" placeholder="Pesquisar..." autocomplete="off" class="w-full outline-none" />
      <button type="submit" class="border-none"><Search /></button>
    </form>
    <main class="bg-zinc-300 min-h-screen">
      <section class="grid grid-cols-1 md:grid-cols-2">
        <article class="flex flex-col max-w-80 w-full">
          <div class="flex flex-col bg-zinc-100 items-center justify-center p-4">
            <p class="self-start">01/02/2024</p>
            <img src="" alt="tempo" />
          </div>
          <div class="grid grid-cols-2 justify-items-center p-4 gap-4 bg-zinc-200">
            <div class="flex items-center gap-x-4"><MoveUp /><span class="text-blue-500">27ºC</span></div>
            <div class="flex items-center gap-x-4"><MoveDown /><span class="text-red-500">13ºC</span></div>
            <div class="flex items-center gap-x-4"><Droplet /><span>0mm</span></div>
            <div class="flex items-center gap-x-4"><Umbrella /><span>10%</span></div>
          </div>
        </article>
      </section>
    </main>
  </div>
</template>

<script setup>
  import { Search, MoveUp, MoveDown, Umbrella, Droplet } from "lucide-vue-next";

</script>

// src/App.jsx
import Header from "./components/Header.jsx"
import SearchBox from "./components/SearchBar.jsx"
import { MoveUp, MoveDown, Droplet, Umbrella } from "lucide-react"

function App() {
  return (
    <>
      <Header />
      <SearchBox />
      <main className="bg-zinc-300 h-screen">
        <p className="text-center text-xl pt-8 pb-8">Previsão para Osasco - SP</p>

        <section className="grid grid-cols-2 justify-items-center">
          <div className="flex flex-col max-w-96 w-full">
            <div className="bg-zinc-100 p-4">
              <p className="mb-4">01/02/2017</p>
              <p class="text-sm">Sol com muitas nuvens durante o dia. Períodos de nublado, com chuvas a qualquer hora.</p>
            </div>
            <div className="bg-zinc-200 grid grid-cols-2 justify-items-center gap-y-4 p-4">
              <div className="flex gap-4">
                <MoveUp />
                <span className="text-blue-600">20°C</span>
              </div>
              <div className="flex gap-4">
                <MoveDown />
                <span className="text-red-600">10°C</span>
              </div>
              <div className="flex gap-4">
                <Droplet fill="#000" />
                <span>10mm</span>
              </div>
              <div className="flex gap-4">
                <Umbrella fill="#000" />
                <span>50%</span>
              </div>
            </div>
          </div>
          <div className="flex flex-col max-w-96 w-full">
            <div className="bg-zinc-100 p-4">
              <p className="mb-4">01/02/2017</p>
              <p class="text-sm">Sol com muitas nuvens durante o dia. Períodos de nublado, com chuvas a qualquer hora.</p>
            </div>
            <div className="bg-zinc-200 grid grid-cols-2 justify-items-center gap-y-4 p-4">
              <div className="flex gap-4">
                <MoveUp />
                <span className="text-blue-600">20°C</span>
              </div>
              <div className="flex gap-4">
                <MoveDown />
                <span className="text-red-600">10°C</span>
              </div>
              <div className="flex gap-4">
                <Droplet fill="#000" />
                <span>10mm</span>
              </div>
              <div className="flex gap-4">
                <Umbrella fill="#000" />
                <span>50%</span>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}

export default App
